name: potato_fries
description: Fries, with a bit of salt
version: 1.0.5+10

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.13.0
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.1+1
  url_launcher: any
  simple_animations: any
  android_flutter_settings:
    git:
      url: https://github.com/AgentFabulous/android_flutter_settings
  provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family:  Logo
      fonts:
        - asset: fonts/Logo.ttf
