name: potato_fries
description: Fries, with a bit of salt
version: 1.2.3+18

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: any
  shared_preferences: any
  url_launcher: any
  simple_animations: any
  android_flutter_settings:
    git:
      url: https://github.com/AgentFabulous/android_flutter_settings
  spicy_components:
    git:
      url: https://github.com/HrX03/SpicyUIComponents
  outline_material_icons: any
  material_design_icons_flutter: any
  provider: any
  animations: any
  video_player: any
  package_info: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family:  Logo
      fonts:
        - asset: fonts/Logo.ttf
    - family:  CustomIcons
      fonts:
       - asset: fonts/CustomIcons.ttf
